import {
  BookingStatus,
  DocumentType,
  LeadStatus,
  PackageStatus,
  PaymentMethod,
  PaymentStatus,
  Priority,
  QuotationStatus,
  SupplierType,
  UserRole,
  VisaStatus,
  WalletTransactionType,
} from "@/generated/prisma/enums";

export type FieldType = "text" | "email" | "tel" | "number" | "date" | "datetime-local" | "textarea" | "select";

export type ModuleField = {
  name: string;
  label: string;
  type?: FieldType;
  required?: boolean;
  options?: string[];
  relation?: "customers" | "staff" | "suppliers" | "agents" | "packages" | "invoices";
  placeholder?: string;
};

export type ModuleConfig = {
  key: string;
  title: string;
  singular: string;
  description: string;
  model: string;
  module: string;
  href: string;
  searchFields: string[];
  tableFields: string[];
  badgeField?: string;
  amountField?: string;
  fields: ModuleField[];
  include?: Record<string, boolean | object>;
  softDelete?: boolean;
};

const enumValues = <T extends Record<string, string>>(value: T) => Object.values(value);

export const moduleConfigs: Record<string, ModuleConfig> = {
  customers: {
    key: "customers",
    title: "Customers",
    singular: "Customer",
    description: "Passport profiles, travel history, documents, invoices, payments, and notes.",
    model: "customer",
    module: "customers",
    href: "/customers",
    searchFields: ["name", "phone", "email", "passportNumber", "nationality"],
    tableFields: ["name", "phone", "email", "nationality", "passportNumber", "createdAt"],
    fields: [
      { name: "name", label: "Full name", required: true },
      { name: "phone", label: "Phone", type: "tel", required: true },
      { name: "email", label: "Email", type: "email" },
      { name: "nationality", label: "Nationality" },
      { name: "dateOfBirth", label: "Date of birth", type: "date" },
      { name: "passportNumber", label: "Passport number" },
      { name: "passportExpiry", label: "Passport expiry", type: "date" },
      { name: "address", label: "Address", type: "textarea" },
      { name: "emergencyContact", label: "Emergency contact" },
      { name: "notes", label: "Internal notes", type: "textarea" },
    ],
    softDelete: true,
  },
  leads: {
    key: "leads",
    title: "Leads",
    singular: "Lead",
    description: "Sales pipeline with follow-ups, priorities, owners, and conversion tracking.",
    model: "lead",
    module: "leads",
    href: "/leads",
    searchFields: ["name", "phone", "email", "source", "interestedDestination"],
    tableFields: ["name", "phone", "interestedDestination", "source", "priority", "status", "nextFollowUpDate"],
    badgeField: "status",
    fields: [
      { name: "name", label: "Lead name", required: true },
      { name: "phone", label: "Phone", type: "tel", required: true },
      { name: "email", label: "Email", type: "email" },
      { name: "source", label: "Source", placeholder: "Facebook, referral, walk-in" },
      { name: "interestedDestination", label: "Destination" },
      { name: "travelDate", label: "Travel date", type: "date" },
      { name: "budget", label: "Budget", type: "number" },
      { name: "assignedStaffId", label: "Assigned staff", type: "select", relation: "staff" },
      { name: "priority", label: "Priority", type: "select", options: enumValues(Priority) },
      { name: "status", label: "Status", type: "select", options: enumValues(LeadStatus) },
      { name: "nextFollowUpDate", label: "Next follow-up", type: "date" },
      { name: "notes", label: "Notes", type: "textarea" },
    ],
    include: { assignedStaff: true },
    softDelete: true,
  },
  "bookings/flights": {
    key: "bookings/flights",
    title: "Flight Bookings",
    singular: "Flight Booking",
    description: "PNR, ticketing, suppliers, payment status, ticket PDFs, refunds, and reissues.",
    model: "flightBooking",
    module: "bookings",
    href: "/bookings/flights",
    searchFields: ["airline", "flightNumber", "departureCity", "arrivalCity", "pnr", "ticketNumber"],
    tableFields: ["customer.name", "airline", "flightNumber", "departureCity", "arrivalCity", "status", "paymentStatus", "totalAmount"],
    badgeField: "status",
    amountField: "totalAmount",
    fields: [
      { name: "customerId", label: "Customer", type: "select", relation: "customers", required: true },
      { name: "airline", label: "Airline", required: true },
      { name: "flightNumber", label: "Flight number", required: true },
      { name: "departureCity", label: "Departure city", required: true },
      { name: "arrivalCity", label: "Arrival city", required: true },
      { name: "departureAt", label: "Departure date/time", type: "datetime-local", required: true },
      { name: "returnAt", label: "Return date/time", type: "datetime-local" },
      { name: "pnr", label: "PNR" },
      { name: "ticketNumber", label: "Ticket number" },
      { name: "supplierId", label: "Supplier", type: "select", relation: "suppliers" },
      { name: "staffAssignedId", label: "Assigned staff", type: "select", relation: "staff" },
      { name: "fareAmount", label: "Fare", type: "number" },
      { name: "tax", label: "Tax", type: "number" },
      { name: "serviceCharge", label: "Service charge", type: "number" },
      { name: "discount", label: "Discount", type: "number" },
      { name: "status", label: "Booking status", type: "select", options: enumValues(BookingStatus) },
      { name: "paymentStatus", label: "Payment status", type: "select", options: enumValues(PaymentStatus) },
      { name: "ticketPdfUrl", label: "Ticket PDF URL" },
    ],
    include: { customer: true, supplier: true, staffAssigned: true },
    softDelete: true,
  },
  visa: {
    key: "visa",
    title: "Visa Applications",
    singular: "Visa Application",
    description: "Embassy workflow, document checklists, appointments, reminders, and status updates.",
    model: "visaApplication",
    module: "visa",
    href: "/visa",
    searchFields: ["country", "visaType", "passportNumber"],
    tableFields: ["customer.name", "country", "visaType", "passportNumber", "status", "paymentStatus", "appointmentDate"],
    badgeField: "status",
    fields: [
      { name: "customerId", label: "Customer", type: "select", relation: "customers", required: true },
      { name: "country", label: "Country", required: true },
      { name: "visaType", label: "Visa type", required: true },
      { name: "purpose", label: "Purpose", type: "textarea" },
      { name: "applicationDate", label: "Application date", type: "date" },
      { name: "appointmentDate", label: "Embassy appointment", type: "date" },
      { name: "expectedDecisionDate", label: "Expected decision", type: "date" },
      { name: "passportNumber", label: "Passport number", required: true },
      { name: "assignedOfficerId", label: "Visa officer", type: "select", relation: "staff" },
      { name: "status", label: "Status", type: "select", options: enumValues(VisaStatus) },
      { name: "paymentStatus", label: "Payment status", type: "select", options: enumValues(PaymentStatus) },
      { name: "notes", label: "Notes", type: "textarea" },
    ],
    include: { customer: true, assignedOfficer: true },
    softDelete: true,
  },
  packages: {
    key: "packages",
    title: "Tour Packages",
    singular: "Tour Package",
    description: "Itineraries, inclusions, availability, package bookings, quotations, and profit tracking.",
    model: "tourPackage",
    module: "packages",
    href: "/packages",
    searchFields: ["title", "destination", "duration"],
    tableFields: ["title", "destination", "duration", "price", "availability", "status"],
    badgeField: "status",
    amountField: "price",
    fields: [
      { name: "title", label: "Package title", required: true },
      { name: "destination", label: "Destination", required: true },
      { name: "duration", label: "Duration", required: true },
      { name: "startDate", label: "Start date", type: "date" },
      { name: "endDate", label: "End date", type: "date" },
      { name: "price", label: "Price", type: "number" },
      { name: "availability", label: "Availability", type: "number" },
      { name: "status", label: "Status", type: "select", options: enumValues(PackageStatus) },
      { name: "hotels", label: "Hotels" },
      { name: "transport", label: "Transport" },
      { name: "meals", label: "Meals" },
      { name: "inclusions", label: "Inclusions", type: "textarea" },
      { name: "exclusions", label: "Exclusions", type: "textarea" },
    ],
    softDelete: true,
  },
  quotations: {
    key: "quotations",
    title: "Quotations",
    singular: "Quotation",
    description: "Flight, visa, package, and custom travel quotes with PDF-ready totals.",
    model: "quotation",
    module: "quotations",
    href: "/quotations",
    searchFields: ["quoteNumber", "title", "type"],
    tableFields: ["quoteNumber", "customer.name", "title", "type", "status", "validUntil", "total"],
    badgeField: "status",
    amountField: "total",
    fields: [
      { name: "customerId", label: "Customer", type: "select", relation: "customers" },
      { name: "tourPackageId", label: "Tour package", type: "select", relation: "packages" },
      { name: "quoteNumber", label: "Quote number", required: true },
      { name: "title", label: "Title", required: true },
      { name: "type", label: "Type", type: "select", options: ["Flight", "Visa", "Tour Package", "Custom"] },
      { name: "tax", label: "Tax", type: "number" },
      { name: "serviceCharge", label: "Service charge", type: "number" },
      { name: "discount", label: "Discount", type: "number" },
      { name: "total", label: "Total", type: "number" },
      { name: "validUntil", label: "Valid until", type: "date" },
      { name: "status", label: "Status", type: "select", options: enumValues(QuotationStatus) },
    ],
    include: { customer: true, tourPackage: true },
    softDelete: true,
  },
  invoices: {
    key: "invoices",
    title: "Invoices",
    singular: "Invoice",
    description: "Billing, due balances, payment capture, print/PDF-ready invoice layouts.",
    model: "invoice",
    module: "invoices",
    href: "/invoices",
    searchFields: ["invoiceNumber"],
    tableFields: ["invoiceNumber", "customer.name", "paymentStatus", "total", "paidAmount", "dueAmount", "dueDate"],
    badgeField: "paymentStatus",
    amountField: "total",
    fields: [
      { name: "customerId", label: "Customer", type: "select", relation: "customers" },
      { name: "invoiceNumber", label: "Invoice number", required: true },
      { name: "tax", label: "Tax", type: "number" },
      { name: "discount", label: "Discount", type: "number" },
      { name: "total", label: "Total", type: "number" },
      { name: "paidAmount", label: "Paid amount", type: "number" },
      { name: "dueAmount", label: "Due amount", type: "number" },
      { name: "paymentStatus", label: "Payment status", type: "select", options: enumValues(PaymentStatus) },
      { name: "dueDate", label: "Due date", type: "date" },
    ],
    include: { customer: true, items: true, payments: true },
    softDelete: true,
  },
  payments: {
    key: "payments",
    title: "Payments",
    singular: "Payment",
    description: "Receipts, outstanding balances, customer ledgers, and agent wallet transactions.",
    model: "payment",
    module: "payments",
    href: "/payments",
    searchFields: ["transactionId", "notes"],
    tableFields: ["customer.name", "invoice.invoiceNumber", "amount", "method", "transactionId", "paymentDate"],
    amountField: "amount",
    fields: [
      { name: "customerId", label: "Customer", type: "select", relation: "customers" },
      { name: "invoiceId", label: "Invoice", type: "select", relation: "invoices" },
      { name: "amount", label: "Amount", type: "number", required: true },
      { name: "method", label: "Payment method", type: "select", options: enumValues(PaymentMethod) },
      { name: "transactionId", label: "Transaction ID" },
      { name: "paymentDate", label: "Payment date", type: "date" },
      { name: "notes", label: "Notes", type: "textarea" },
      { name: "receiptFile", label: "Receipt file URL" },
    ],
    include: { customer: true, invoice: true, receivedBy: true },
    softDelete: true,
  },
  agents: {
    key: "agents",
    title: "B2B Agents",
    singular: "Agent",
    description: "Sub-agent approvals, commission rates, credit limits, sales, ledgers, and wallets.",
    model: "agent",
    module: "agents",
    href: "/agents",
    searchFields: ["companyName", "contactPerson", "email", "phone"],
    tableFields: ["companyName", "contactPerson", "email", "phone", "commissionRate", "creditLimit", "isApproved"],
    fields: [
      { name: "companyName", label: "Company name", required: true },
      { name: "contactPerson", label: "Contact person", required: true },
      { name: "email", label: "Email", type: "email", required: true },
      { name: "phone", label: "Phone", type: "tel", required: true },
      { name: "address", label: "Address", type: "textarea" },
      { name: "commissionRate", label: "Commission rate", type: "number" },
      { name: "creditLimit", label: "Credit limit", type: "number" },
    ],
    include: { wallet: true },
    softDelete: true,
  },
  wallet: {
    key: "wallet",
    title: "Wallet Transactions",
    singular: "Wallet Transaction",
    description: "Deposits, approvals, booking debits, commission credits, refunds, and statements.",
    model: "walletTransaction",
    module: "wallet",
    href: "/wallet",
    searchFields: ["reference", "status", "notes"],
    tableFields: ["wallet.agent.companyName", "type", "amount", "reference", "status", "createdAt"],
    badgeField: "status",
    amountField: "amount",
    fields: [
      { name: "agentId", label: "Agent", type: "select", relation: "agents", required: true },
      { name: "type", label: "Type", type: "select", options: enumValues(WalletTransactionType) },
      { name: "amount", label: "Amount", type: "number", required: true },
      { name: "reference", label: "Reference" },
      { name: "status", label: "Status", type: "select", options: ["Pending", "Approved", "Rejected", "Completed"] },
      { name: "notes", label: "Notes", type: "textarea" },
    ],
    include: { wallet: { include: { agent: true } } },
  },
  suppliers: {
    key: "suppliers",
    title: "Suppliers",
    singular: "Supplier",
    description: "Airline, hotel, visa, transport, and tour suppliers with ledgers and payables.",
    model: "supplier",
    module: "suppliers",
    href: "/suppliers",
    searchFields: ["name", "contactPerson", "phone", "email"],
    tableFields: ["name", "type", "contactPerson", "phone", "email", "openingBalance"],
    badgeField: "type",
    amountField: "openingBalance",
    fields: [
      { name: "type", label: "Type", type: "select", options: enumValues(SupplierType) },
      { name: "name", label: "Supplier name", required: true },
      { name: "contactPerson", label: "Contact person" },
      { name: "phone", label: "Phone", type: "tel" },
      { name: "email", label: "Email", type: "email" },
      { name: "address", label: "Address", type: "textarea" },
      { name: "openingBalance", label: "Opening balance", type: "number" },
      { name: "notes", label: "Notes", type: "textarea" },
    ],
    softDelete: true,
  },
  documents: {
    key: "documents",
    title: "Documents",
    singular: "Document",
    description: "Secure document storage linked to customers, bookings, visas, invoices, and packages.",
    model: "document",
    module: "documents",
    href: "/documents",
    searchFields: ["title", "fileUrl", "mimeType"],
    tableFields: ["title", "type", "customer.name", "expiryDate", "fileUrl", "createdAt"],
    badgeField: "type",
    fields: [
      { name: "customerId", label: "Customer", type: "select", relation: "customers" },
      { name: "type", label: "Document type", type: "select", options: enumValues(DocumentType) },
      { name: "title", label: "Title", required: true },
      { name: "fileUrl", label: "File URL", required: true },
      { name: "mimeType", label: "MIME type" },
      { name: "expiryDate", label: "Expiry date", type: "date" },
    ],
    include: { customer: true, uploadedBy: true },
    softDelete: true,
  },
  staff: {
    key: "staff",
    title: "Staff",
    singular: "Staff Member",
    description: "Team members, role assignments, account status, activity, and performance views.",
    model: "user",
    module: "staff",
    href: "/staff",
    searchFields: ["name", "email", "phone", "title"],
    tableFields: ["name", "email", "role.name", "title", "phone", "isActive", "lastLoginAt"],
    badgeField: "role.name",
    fields: [
      { name: "name", label: "Name", required: true },
      { name: "email", label: "Email", type: "email", required: true },
      { name: "phone", label: "Phone", type: "tel" },
      { name: "title", label: "Title" },
      { name: "roleName", label: "Role", type: "select", options: enumValues(UserRole) },
    ],
    include: { role: true },
    softDelete: true,
  },
};

export const moduleList = Object.values(moduleConfigs);
